version: '3.7'

services:
  application:
    container_name: ${BCKND_NAME}_APPLICATION
    build: .
    environment:
      - BCKND_NAME=${BCKND_NAME}
      - BCKND_PORT=${BCKND_PORT}
      - BCKND_ENV0=${BCKND_ENV0}
      - JWT_SCRT=${JWT_SCRT}
      - JWT_EXPI=${JWT_EXPI}
      - DTBS_HOST=${DTBS_HOST}
      - DTBS_PORT=${DTBS_PORT}
      - DTBS_NAME=${DTBS_NAME}
      - DTBS_USER=${DTBS_USER}
      - DTBS_PSWD=${DTBS_PSWD}
      - DTBS_LOGS=${DTBS_LOGS}
      - DTBS_VOL0=${DTBS_VOL0}
      - SNGRD_APIK=${SNGRD_APIK}
      - SNGRD_MAIL=${SNGRD_MAIL}
    ports:
      - 80:${BCKND_PORT}
  database:
    image: postgres
    container_name: ${BCKND_NAME}_POSTGRESS_DB
    restart: always
    environment:
      - POSTGRES_DB=${DTBS_NAME}
      - POSTGRES_USER=${DTBS_USER}
      - POSTGRES_PASSWORD=${DTBS_PSWD}
      - TZ=America/Santo_Domingo
    volumes:
      - ${DTBS_VOL0}:/var/lib/postgresql/data
    ports:
      - ${DTBS_PORT}:5432
