name: Publish Docker image
on:
  push:
    branches:
      - master
env:
  AZURE_WEBAPP_NAME: si-app

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: jeffreyart1/si
          tag_with_ref: true

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: jeffreyart1/si

      - name: Setup env variables
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
              {
                  "name": "BCKND_PORT",
                  "value": "${{ secrets.APP_PORT }}",
                  "slotSetting": false
              },
              {
                  "name": "BCKND_ENV0",
                  "value": "${{ secrets.APP_ENV }}",
                  "slotSetting": false
              },
              {
                  "name": "DTBS_HOST",
                  "value": "${{ secrets.DB_HOST }}",
                  "slotSetting": false
              },
              {
                  "name": "DTBS_PORT",
                  "value": "${{ secrets.DB_PORT }}",
                  "slotSetting": false
              },
              {
                  "name": "DTBS_USER",
                  "value": "${{ secrets.DB_USER }}",
                  "slotSetting": false
              },
              {
                  "name": "DTBS_PSWD",
                  "value": "${{ secrets.DB_PASSWORD }}",
                  "slotSetting": false
              },
              {
                  "name": "DTBS_NAME",
                  "value": "${{ secrets.DB_NAME }}",
                  "slotSetting": false
              },
              {
                  "name": "SNGRD_APIK",
                  "value": "${{ secrets.SENDGRID_API_KEY }}",
                  "slotSetting": false
              },
              {
                  "name": "JWT_SCRT",
                  "value": "${{ secrets.JWT_SCRT }}",
                  "slotSetting": false
              },
              {
                  "name": "JWT_EXPI",
                  "value": "${{ secrets.JWT_EXPI }}",
                  "slotSetting": false
              }
            ]

      - name: Azure logout
        run: |
          az logout
